# Generated by Django 4.0.3 on 2022-03-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='modified_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_qty',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
